// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMenu.Services.RecipeAPI.Data;

#nullable disable

namespace SmartMenu.Services.RecipeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMenu.Services.RecipeAPI.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CategoryName = "Appetizer",
                            Description = "Toasted bread topped with fresh tomatoes, basil, garlic, and a drizzle of olive oil.<br/> A classic Italian appetizer.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Bruschetta",
                            Price = 7.5
                        },
                        new
                        {
                            RecipeId = 2,
                            CategoryName = "Appetizer",
                            Description = "Fresh mozzarella, tomatoes, and basil, drizzled with balsamic glaze.<br/> A light and refreshing start to any meal.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Caprese Salad",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            RecipeId = 3,
                            CategoryName = "Dessert",
                            Description = "A classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cheese, dusted with cocoa powder.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Tiramisu",
                            Price = 10.99
                        },
                        new
                        {
                            RecipeId = 4,
                            CategoryName = "Entree",
                            Description = "Layered pasta with rich Bolognese sauce, creamy béchamel, and melted cheese.<br/> A hearty and satisfying Italian main course.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Lasagna",
                            Price = 14.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
